/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.schoolproject.movie_rentaldashboard;

import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.text.SimpleDateFormat;

/**
 *
 * @author Yurine Rose Hanazono
 */
public class AdminDashboard extends javax.swing.JFrame {
    public JFileChooser fileChooser;
    public ArrayList<String> movieDetails;

    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    Date currentDate = new Date();
    String formattedDateTime = dateFormat.format(currentDate);

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        this.movieDetails = new ArrayList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Movies = new javax.swing.JPanel();
        movie_upload = new javax.swing.JPanel();
        label_MovieID = new javax.swing.JLabel();
        tfMovieID = new javax.swing.JTextField();
        label_Title = new javax.swing.JLabel();
        tfTitle = new javax.swing.JTextField();
        label_Cast = new javax.swing.JLabel();
        tfCast = new javax.swing.JTextField();
        label_Genre = new javax.swing.JLabel();
        tfGenre = new javax.swing.JTextField();
        label_Runtime = new javax.swing.JLabel();
        tfRuntime = new javax.swing.JTextField();
        label_AgeRestriction = new javax.swing.JLabel();
        tfAgeRestriction = new javax.swing.JTextField();
        label_Description = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescription = new javax.swing.JTextArea();
        buttonSelectPNG = new javax.swing.JButton();
        label_Image = new javax.swing.JLabel();
        buttonSubmit = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        label_imagename = new javax.swing.JTextArea();
        movie_db = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        movie_table = new javax.swing.JTable();
        buttonThumbnail = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonDisplay = new javax.swing.JButton();
        User = new javax.swing.JPanel();
        movie_upload1 = new javax.swing.JPanel();
        label_UserID = new javax.swing.JLabel();
        tfUserID = new javax.swing.JTextField();
        label_Password = new javax.swing.JLabel();
        tfPassword = new javax.swing.JTextField();
        label_Name = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        label_ContactNo = new javax.swing.JLabel();
        tfContactNo = new javax.swing.JTextField();
        label_Email = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        movie_information = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        user_movie_table = new javax.swing.JTable();
        registered_users = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        user_table = new javax.swing.JTable();
        buttonUserLoad = new javax.swing.JButton();
        buttonUserDelete = new javax.swing.JButton();
        Logs = new javax.swing.JPanel();
        logs = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        taLogs = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Dashboard");

        jPanel1.setBackground(new java.awt.Color(33, 32, 30));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        Movies.setBackground(new java.awt.Color(33, 32, 30));

        movie_upload.setBackground(new java.awt.Color(33, 32, 30));
        movie_upload.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "Movie Upload", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        movie_upload.setForeground(new java.awt.Color(33, 32, 30));

        label_MovieID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_MovieID.setForeground(new java.awt.Color(255, 255, 255));
        label_MovieID.setText("Movie ID");

        tfMovieID.setEditable(false);
        tfMovieID.setBackground(new java.awt.Color(33, 32, 30));
        tfMovieID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfMovieID.setForeground(new java.awt.Color(255, 255, 255));
        tfMovieID.setText("12345");
        tfMovieID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tfMovieID.setPreferredSize(new java.awt.Dimension(72, 25));
        tfMovieID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMovieIDActionPerformed(evt);
            }
        });

        label_Title.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_Title.setForeground(new java.awt.Color(255, 255, 255));
        label_Title.setText("Title");

        tfTitle.setBackground(new java.awt.Color(33, 32, 30));
        tfTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfTitle.setForeground(new java.awt.Color(255, 255, 255));
        tfTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tfTitle.setPreferredSize(new java.awt.Dimension(72, 25));
        tfTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTitleActionPerformed(evt);
            }
        });

        label_Cast.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_Cast.setForeground(new java.awt.Color(255, 255, 255));
        label_Cast.setText("Cast");

        tfCast.setBackground(new java.awt.Color(33, 32, 30));
        tfCast.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfCast.setForeground(new java.awt.Color(255, 255, 255));
        tfCast.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tfCast.setPreferredSize(new java.awt.Dimension(72, 25));

        label_Genre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_Genre.setForeground(new java.awt.Color(255, 255, 255));
        label_Genre.setText("Genre");

        tfGenre.setBackground(new java.awt.Color(33, 32, 30));
        tfGenre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfGenre.setForeground(new java.awt.Color(255, 255, 255));
        tfGenre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tfGenre.setPreferredSize(new java.awt.Dimension(72, 25));
        tfGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGenreActionPerformed(evt);
            }
        });

        label_Runtime.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_Runtime.setForeground(new java.awt.Color(255, 255, 255));
        label_Runtime.setText("Runtime");

        tfRuntime.setBackground(new java.awt.Color(33, 32, 30));
        tfRuntime.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfRuntime.setForeground(new java.awt.Color(255, 255, 255));
        tfRuntime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tfRuntime.setPreferredSize(new java.awt.Dimension(72, 25));

        label_AgeRestriction.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_AgeRestriction.setForeground(new java.awt.Color(255, 255, 255));
        label_AgeRestriction.setText("Age Restriction");

        tfAgeRestriction.setBackground(new java.awt.Color(33, 32, 30));
        tfAgeRestriction.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfAgeRestriction.setForeground(new java.awt.Color(255, 255, 255));
        tfAgeRestriction.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tfAgeRestriction.setPreferredSize(new java.awt.Dimension(72, 25));

        label_Description.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_Description.setForeground(new java.awt.Color(255, 255, 255));
        label_Description.setText("Description");

        taDescription.setBackground(new java.awt.Color(33, 32, 30));
        taDescription.setColumns(20);
        taDescription.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        taDescription.setForeground(new java.awt.Color(255, 255, 255));
        taDescription.setLineWrap(true);
        taDescription.setRows(5);
        taDescription.setToolTipText("");
        taDescription.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jScrollPane1.setViewportView(taDescription);

        buttonSelectPNG.setBackground(new java.awt.Color(33, 32, 30));
        buttonSelectPNG.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonSelectPNG.setForeground(new java.awt.Color(255, 255, 255));
        buttonSelectPNG.setText("Select PNG");
        buttonSelectPNG.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        buttonSelectPNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSelectPNGActionPerformed(evt);
            }
        });

        label_Image.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_Image.setForeground(new java.awt.Color(255, 255, 255));
        label_Image.setText("Image");

        buttonSubmit.setBackground(new java.awt.Color(33, 32, 30));
        buttonSubmit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonSubmit.setForeground(new java.awt.Color(255, 255, 255));
        buttonSubmit.setText("Submit");
        buttonSubmit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });

        label_imagename.setEditable(false);
        label_imagename.setBackground(new java.awt.Color(33, 32, 30));
        label_imagename.setColumns(7);
        label_imagename.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_imagename.setForeground(new java.awt.Color(255, 255, 255));
        label_imagename.setLineWrap(true);
        label_imagename.setRows(5);
        label_imagename.setText("Image:");
        label_imagename.setBorder(null);
        label_imagename.setCaretColor(new java.awt.Color(33, 32, 30));
        label_imagename.setCaretPosition(0);
        jScrollPane6.setViewportView(label_imagename);

        javax.swing.GroupLayout movie_uploadLayout = new javax.swing.GroupLayout(movie_upload);
        movie_upload.setLayout(movie_uploadLayout);
        movie_uploadLayout.setHorizontalGroup(
            movie_uploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie_uploadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(movie_uploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(movie_uploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, movie_uploadLayout.createSequentialGroup()
                            .addComponent(label_Runtime)
                            .addGap(6, 6, 6))
                        .addComponent(label_MovieID)
                        .addComponent(label_Genre)
                        .addComponent(label_Cast)
                        .addComponent(label_Title))
                    .addGroup(movie_uploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(buttonSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_Description, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label_AgeRestriction, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_Image, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(buttonSelectPNG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(movie_uploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfAgeRestriction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                    .addComponent(tfRuntime, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                    .addComponent(tfMovieID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfGenre, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                    .addComponent(tfTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                    .addComponent(tfCast, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        movie_uploadLayout.setVerticalGroup(
            movie_uploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie_uploadLayout.createSequentialGroup()
                .addGroup(movie_uploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_MovieID)
                    .addComponent(tfMovieID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(movie_uploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Title)
                    .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(movie_uploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Cast)
                    .addComponent(tfCast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(movie_uploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Genre)
                    .addComponent(tfGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(movie_uploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Runtime)
                    .addComponent(tfRuntime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(movie_uploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_AgeRestriction)
                    .addComponent(tfAgeRestriction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(movie_uploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(movie_uploadLayout.createSequentialGroup()
                        .addComponent(label_Description)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonSubmit)
                        .addGap(24, 24, 24)
                        .addComponent(label_Image)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSelectPNG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        movie_db.setBackground(new java.awt.Color(33, 32, 30));
        movie_db.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "Movie Database", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jScrollPane2.setBackground(new java.awt.Color(33, 32, 30));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        movie_table.setBackground(new java.awt.Color(33, 32, 30));
        movie_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        movie_table.setForeground(new java.awt.Color(255, 255, 255));
        movie_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie_ID", "Title", "Cast", "Genre", "Runtime", "Age_Restriction", "Description"
            }
        ));
        jScrollPane2.setViewportView(movie_table);

        buttonThumbnail.setBackground(new java.awt.Color(33, 32, 30));
        buttonThumbnail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonThumbnail.setForeground(new java.awt.Color(255, 255, 255));
        buttonThumbnail.setText("Thumbnail");
        buttonThumbnail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        buttonDelete.setBackground(new java.awt.Color(33, 32, 30));
        buttonDelete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonDelete.setForeground(new java.awt.Color(255, 255, 255));
        buttonDelete.setText("Delete");
        buttonDelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonDisplay.setBackground(new java.awt.Color(33, 32, 30));
        buttonDisplay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonDisplay.setForeground(new java.awt.Color(255, 255, 255));
        buttonDisplay.setText("Display");
        buttonDisplay.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        javax.swing.GroupLayout movie_dbLayout = new javax.swing.GroupLayout(movie_db);
        movie_db.setLayout(movie_dbLayout);
        movie_dbLayout.setHorizontalGroup(
            movie_dbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
            .addGroup(movie_dbLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonThumbnail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        movie_dbLayout.setVerticalGroup(
            movie_dbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie_dbLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(movie_dbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDelete)
                    .addComponent(buttonThumbnail)
                    .addComponent(buttonDisplay))
                .addContainerGap())
        );

        javax.swing.GroupLayout MoviesLayout = new javax.swing.GroupLayout(Movies);
        Movies.setLayout(MoviesLayout);
        MoviesLayout.setHorizontalGroup(
            MoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MoviesLayout.createSequentialGroup()
                .addComponent(movie_upload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(movie_db, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MoviesLayout.setVerticalGroup(
            MoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(movie_upload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(movie_db, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Movies", Movies);

        User.setBackground(new java.awt.Color(33, 32, 30));

        movie_upload1.setBackground(new java.awt.Color(33, 32, 30));
        movie_upload1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "User Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        movie_upload1.setForeground(new java.awt.Color(33, 32, 30));

        label_UserID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_UserID.setForeground(new java.awt.Color(255, 255, 255));
        label_UserID.setText("User ID/Username");

        tfUserID.setEditable(false);
        tfUserID.setBackground(new java.awt.Color(33, 32, 30));
        tfUserID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfUserID.setForeground(new java.awt.Color(255, 255, 255));
        tfUserID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tfUserID.setPreferredSize(new java.awt.Dimension(72, 25));
        tfUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserIDActionPerformed(evt);
            }
        });

        label_Password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_Password.setForeground(new java.awt.Color(255, 255, 255));
        label_Password.setText("Password");

        tfPassword.setBackground(new java.awt.Color(33, 32, 30));
        tfPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfPassword.setForeground(new java.awt.Color(255, 255, 255));
        tfPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tfPassword.setPreferredSize(new java.awt.Dimension(72, 25));
        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });

        label_Name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_Name.setForeground(new java.awt.Color(255, 255, 255));
        label_Name.setText("Name");

        tfName.setBackground(new java.awt.Color(33, 32, 30));
        tfName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfName.setForeground(new java.awt.Color(255, 255, 255));
        tfName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tfName.setPreferredSize(new java.awt.Dimension(72, 25));

        label_ContactNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_ContactNo.setForeground(new java.awt.Color(255, 255, 255));
        label_ContactNo.setText("Contact No.");

        tfContactNo.setBackground(new java.awt.Color(33, 32, 30));
        tfContactNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfContactNo.setForeground(new java.awt.Color(255, 255, 255));
        tfContactNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tfContactNo.setPreferredSize(new java.awt.Dimension(72, 25));
        tfContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContactNoActionPerformed(evt);
            }
        });

        label_Email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_Email.setForeground(new java.awt.Color(255, 255, 255));
        label_Email.setText("Email");

        tfEmail.setBackground(new java.awt.Color(33, 32, 30));
        tfEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfEmail.setForeground(new java.awt.Color(255, 255, 255));
        tfEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tfEmail.setPreferredSize(new java.awt.Dimension(72, 25));

        movie_information.setBackground(new java.awt.Color(33, 32, 30));
        movie_information.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Movies Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jScrollPane3.setBackground(new java.awt.Color(33, 32, 30));
        jScrollPane3.setForeground(new java.awt.Color(255, 255, 255));

        user_movie_table.setBackground(new java.awt.Color(33, 32, 30));
        user_movie_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        user_movie_table.setForeground(new java.awt.Color(255, 255, 255));
        user_movie_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie_ID", "Title", "Type", "Date/if Rented", "Due_Date", "Date/if Bought"
            }
        ));
        jScrollPane3.setViewportView(user_movie_table);

        javax.swing.GroupLayout movie_informationLayout = new javax.swing.GroupLayout(movie_information);
        movie_information.setLayout(movie_informationLayout);
        movie_informationLayout.setHorizontalGroup(
            movie_informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(movie_informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(movie_informationLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        movie_informationLayout.setVerticalGroup(
            movie_informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(movie_informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(movie_informationLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout movie_upload1Layout = new javax.swing.GroupLayout(movie_upload1);
        movie_upload1.setLayout(movie_upload1Layout);
        movie_upload1Layout.setHorizontalGroup(
            movie_upload1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie_upload1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(movie_upload1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(movie_information, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(movie_upload1Layout.createSequentialGroup()
                        .addGroup(movie_upload1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_UserID)
                            .addComponent(label_ContactNo)
                            .addComponent(label_Name)
                            .addComponent(label_Password)
                            .addComponent(label_Email))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 70, Short.MAX_VALUE)
                        .addGroup(movie_upload1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                            .addComponent(tfUserID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfContactNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        movie_upload1Layout.setVerticalGroup(
            movie_upload1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie_upload1Layout.createSequentialGroup()
                .addGroup(movie_upload1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_UserID)
                    .addComponent(tfUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(movie_upload1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Password)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(movie_upload1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Name)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(movie_upload1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_ContactNo)
                    .addComponent(tfContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(movie_upload1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(movie_information, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        registered_users.setBackground(new java.awt.Color(33, 32, 30));
        registered_users.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "Registered Users", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jScrollPane4.setBackground(new java.awt.Color(33, 32, 30));
        jScrollPane4.setForeground(new java.awt.Color(255, 255, 255));

        user_table.setBackground(new java.awt.Color(33, 32, 30));
        user_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        user_table.setForeground(new java.awt.Color(255, 255, 255));
        user_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password", "Name", "Contact", "Email"
            }
        ));
        jScrollPane4.setViewportView(user_table);

        buttonUserLoad.setBackground(new java.awt.Color(33, 32, 30));
        buttonUserLoad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonUserLoad.setForeground(new java.awt.Color(255, 255, 255));
        buttonUserLoad.setText("Load");
        buttonUserLoad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        buttonUserLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUserLoadActionPerformed(evt);
            }
        });

        buttonUserDelete.setBackground(new java.awt.Color(33, 32, 30));
        buttonUserDelete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonUserDelete.setForeground(new java.awt.Color(255, 255, 255));
        buttonUserDelete.setText("Delete");
        buttonUserDelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        buttonUserDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUserDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registered_usersLayout = new javax.swing.GroupLayout(registered_users);
        registered_users.setLayout(registered_usersLayout);
        registered_usersLayout.setHorizontalGroup(
            registered_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
            .addGroup(registered_usersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonUserDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonUserLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registered_usersLayout.setVerticalGroup(
            registered_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registered_usersLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registered_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonUserDelete)
                    .addComponent(buttonUserLoad))
                .addContainerGap())
        );

        javax.swing.GroupLayout UserLayout = new javax.swing.GroupLayout(User);
        User.setLayout(UserLayout);
        UserLayout.setHorizontalGroup(
            UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserLayout.createSequentialGroup()
                .addComponent(movie_upload1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registered_users, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UserLayout.setVerticalGroup(
            UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(movie_upload1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(registered_users, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("User", User);

        Logs.setBackground(new java.awt.Color(33, 32, 30));

        logs.setBackground(new java.awt.Color(33, 32, 30));
        logs.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "Logs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        logs.setForeground(new java.awt.Color(33, 32, 30));

        taLogs.setBackground(new java.awt.Color(33, 32, 30));
        taLogs.setColumns(20);
        taLogs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        taLogs.setForeground(new java.awt.Color(255, 255, 255));
        taLogs.setLineWrap(true);
        taLogs.setRows(5);
        taLogs.setToolTipText("");
        taLogs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jScrollPane5.setViewportView(taLogs);

        javax.swing.GroupLayout logsLayout = new javax.swing.GroupLayout(logs);
        logs.setLayout(logsLayout);
        logsLayout.setHorizontalGroup(
            logsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1099, Short.MAX_VALUE)
                .addContainerGap())
        );
        logsLayout.setVerticalGroup(
            logsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logsLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout LogsLayout = new javax.swing.GroupLayout(Logs);
        Logs.setLayout(LogsLayout);
        LogsLayout.setHorizontalGroup(
            LogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LogsLayout.setVerticalGroup(
            LogsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Logs", Logs);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTitleActionPerformed

    private void tfGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGenreActionPerformed

    private void tfMovieIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMovieIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMovieIDActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void tfUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserIDActionPerformed

    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasswordActionPerformed

    private void tfContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfContactNoActionPerformed

    private void buttonUserDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUserDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonUserDeleteActionPerformed

    private void buttonUserLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUserLoadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonUserLoadActionPerformed

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        // TODO add your handling code here:
        int Movie_ID = Integer.parseInt(tfMovieID.getText());
        String Movie_Title = tfTitle.getText();
        String Movie_Cast = tfCast.getText();
        String Movie_Genre = tfGenre.getText();
        String Movie_Runtime = tfRuntime.getText();
        String Movie_AgeDescription = tfAgeRestriction.getText();
        String Movie_Description = taDescription.getText();
        String selectedFile = fileChooser.getSelectedFile().getAbsolutePath();
    
        // Add movie details to the list
        movieDetails.add(String.valueOf(Movie_ID));
        movieDetails.add(Movie_Title);
        movieDetails.add(Movie_Cast);
        movieDetails.add(Movie_Genre);
        movieDetails.add(Movie_Runtime);
        movieDetails.add(Movie_AgeDescription);
        movieDetails.add(Movie_Description);
        movieDetails.add(selectedFile);

        addMovieToTable();
        //insertMovieToDatabase();

        taLogs.append("[" + formattedDateTime + "]" + "Added: New movie added: "+ Movie_Title +"\n");
    }//GEN-LAST:event_buttonSubmitActionPerformed

    private void buttonSelectPNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelectPNGActionPerformed
        // TODO add your handling code here:
        fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PNG Files", "png");
        fileChooser.setFileFilter(filter);

        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String fileName = selectedFile.getName();
            label_imagename.setText("Image: "+fileName);
            System.out.println("Selected file: " + fileName);
        }
    }//GEN-LAST:event_buttonSelectPNGActionPerformed

    private void addMovieToTable() {
        // Extract movie details
        int movieID = Integer.parseInt(movieDetails.get(0));
        String movieTitle = movieDetails.get(1);
        String movieCast = movieDetails.get(2);
        String movieGenre = movieDetails.get(3);
        String movieRuntime = movieDetails.get(4);
        String movieAgeDescription = movieDetails.get(5);
        String movieDescription = movieDetails.get(6);

        // Get the table model of the movie_table
        DefaultTableModel model = (DefaultTableModel) movie_table.getModel();

        // Add movie details to the table model
        Object[] rowData = {movieID, movieTitle, movieCast, movieGenre, movieRuntime, movieAgeDescription, movieDescription};
        model.addRow(rowData);
    }

    /*private void insertMovieToDatabase() {
        try {
            // Establish database connection
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/your_database", "username", "password");

            // Prepare SQL statement
            String sql = "INSERT INTO movies (movie_id, title, cast, genre, runtime, age_description, description) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement statement = connection.prepareStatement(sql);

            // Set parameters
            statement.setInt(1, Integer.parseInt(movieDetails.get(0))); // Movie ID
            statement.setString(2, movieDetails.get(1)); // Movie Title
            statement.setString(3, movieDetails.get(2)); // Movie Cast
            statement.setString(4, movieDetails.get(3)); // Movie Genre
            statement.setString(5, movieDetails.get(4)); // Movie Runtime
            statement.setString(6, movieDetails.get(5)); // Movie Age Description
            statement.setString(7, movieDetails.get(6)); // Movie Description

            // Execute the insert statement
            statement.executeUpdate();

            // Close the connection
            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }*/

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Logs;
    private javax.swing.JPanel Movies;
    private javax.swing.JPanel User;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonDisplay;
    private javax.swing.JButton buttonSelectPNG;
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JButton buttonThumbnail;
    private javax.swing.JButton buttonUserDelete;
    private javax.swing.JButton buttonUserLoad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label_AgeRestriction;
    private javax.swing.JLabel label_Cast;
    private javax.swing.JLabel label_ContactNo;
    private javax.swing.JLabel label_Description;
    private javax.swing.JLabel label_Email;
    private javax.swing.JLabel label_Genre;
    private javax.swing.JLabel label_Image;
    private javax.swing.JLabel label_MovieID;
    private javax.swing.JLabel label_Name;
    private javax.swing.JLabel label_Password;
    private javax.swing.JLabel label_Runtime;
    private javax.swing.JLabel label_Title;
    private javax.swing.JLabel label_UserID;
    private javax.swing.JTextArea label_imagename;
    private javax.swing.JPanel logs;
    private javax.swing.JPanel movie_db;
    private javax.swing.JPanel movie_information;
    private javax.swing.JTable movie_table;
    private javax.swing.JPanel movie_upload;
    private javax.swing.JPanel movie_upload1;
    private javax.swing.JPanel registered_users;
    private javax.swing.JTextArea taDescription;
    private javax.swing.JTextArea taLogs;
    private javax.swing.JTextField tfAgeRestriction;
    private javax.swing.JTextField tfCast;
    private javax.swing.JTextField tfContactNo;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfGenre;
    private javax.swing.JTextField tfMovieID;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfRuntime;
    private javax.swing.JTextField tfTitle;
    private javax.swing.JTextField tfUserID;
    private javax.swing.JTable user_movie_table;
    private javax.swing.JTable user_table;
    // End of variables declaration//GEN-END:variables

}
