-- Populate the database

Use cinematique;

INSERT INTO Movies (title, year, genre, duration, ageRating, cast, description, image, price)
VALUES ('Alice in Wonderland', 2010, 'Fantasy', 75, 'G', 'Kathryn Beaumont, Ed Wynn, Richard Haydn',
        'Alice stumbles into the world of Wonderland. Will she get home? Not if the Queen of Hearts has her way.',
        '1.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Coraline', 2009, 'Fantasy', 100, 'PG', 'Dakota Fanning, Teri Hatcher, John Hodgman',
        'An adventurous 11-year-old girl finds another world that is a strangely idealized version of her frustrating home, but it has sinister secrets.',
        '2.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Harry Potter and the Philosopher\'s Stone', 2001, 'Fantasy', 152, 'PG',
        'Daniel Radcliffe, Rupert Grint, Emma Watson',
        'An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family, and the terrible evil that haunts the magical world.',
        '3.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Harry Potter and the Chamber of Secrets', 2002, 'Fantasy', 161, 'PG',
        'Daniel Radcliffe, Rupert Grint, Emma Watson',
        'An ancient prophecy seems to be coming true when a mysterious presence begins stalking the corridors of a school of magic and leaving its victims paralyzed.',
        '4.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Harry Potter and the Prisoner of Azkaban', 2004, 'Fantasy', 142, 'PG',
        'Daniel Radcliffe, Rupert Grint, Emma Watson',
        'It\'s Harry\'s third year at Hogwarts; not only does he have a new "Defense Against the Dark Arts" teacher, but there is also trouble brewing.',
        '5.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Harry Potter and the Goblet of Fire', 2005, 'Fantasy', 157, 'PG',
        'Daniel Radcliffe, Rupert Grint, Emma Watson',
        'Harry Potter finds himself competing in a hazardous tournament between rival schools of magic, but he is distracted by recurring nightmares.',
        '6.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Harry Potter and the Order of the Phoenix', 2007, 'Fantasy', 138, 'PG',
        'Daniel Radcliffe, Rupert Grint, Emma Watson',
        'With their warning about Lord Voldemort\'s return scoffed at, Harry and Dumbledore are targeted by the Wizard authorities as an authoritarian bureaucrat slowly seizes power at Hogwarts.',
        '7.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Stardust', 2007, 'Fantasy', 127, 'PG', 'Charlie Cox, Claire Danes, Sienna Miller',
        'In a countryside town bordering on a magical land, a young man makes a promise to his beloved that he\'ll retrieve a fallen star by venturing into the magical realm.',
        '8.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('The Chronicles of Narnia: Prince Caspian', 2008, 'Fantasy', 150, 'PG',
        'Ben Barnes, Skandar Keynes, Georgie Henley',
        'The Pevensie siblings return to Narnia, where they are enlisted to once again help ward off an evil king and restore the rightful heir to the land\'s throne, Prince Caspian.',
        '9.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('"The Chronicles of Narnia: The Lion, the Witch and the Wardrobe"', 2005, 'Fantasy', 143, 'PG',
        'Tilda Swinton, Georgie Henley, William Moseley',
        'Four kids travel through a wardrobe to the land of Narnia and learn of their destiny to free it with the guidance of a mystical lion.',
        '10.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('The Dark Crystal', 1982, 'Fantasy', 93, 'PG', 'Jim Henson, Kathryn Mullen, Frank Oz',
        'On another planet in the distant past, a Gelfling embarks on a quest to find the missing shard of a magical crystal, and so restore order to his world.',
        '11.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('The Lord of the Rings: The Fellowship of the Ring', 2001, 'Fantasy', 178, 'PG',
        'Elijah Wood, Ian McKellen, Orlando Bloom',
        'A young hobbit, Frodo, who has found the One Ring that belongs to the Dark Lord Sauron, begins his journey with eight companions to Mount Doom, the only place where it can be destroyed.',
        '12.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('The NeverEnding Story', 1984, 'Fantasy', 102, 'PG-13', 'Noah Hathaway, Barret Oliver, Tami Stronach',
        'A troubled boy dives into a wondrous fantasy world through the pages of a mysterious book.', '13.jpg',
        ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('The Shape of Water', 2017, 'Fantasy', 123, 'R', 'Sally Hawkins, Octavia Spencer, Michael Shannon',
        'At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.',
        '14.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('The Wizard of Oz', 1939, 'Fantasy', 102, 'PG', 'Judy Garland, Frank Morgan, Ray Bolger',
        'A young girl is swept away to a magical land in a tornado and embarks on a quest to see the Wizard who can help her return home.',
        '15.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Avatar', 2009, 'Action', 162, 'PG-13', 'Sam Worthington, Zoe Saldana, Sigourney Weaver',
        'A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.',
        '1.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Black Panther', 2018, 'Action', 134, 'PG-13', 'Chadwick Boseman, Michael B. Jordan, Lupita Nyong\'o',
        'T\'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country\'s past.',
        '2.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Die Hard', 1988, 'Action', 132, 'R', 'Bruce Willis, Alan Rickman, Bonnie Bedelia',
        'An NYPD officer tries to save his wife and several others taken hostage by German terrorists during a Christmas party at the Nakatomi Plaza in Los Angeles.',
        '3.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Ghostbusters', 1984, 'Action', 105, 'PG', 'Bill Murray, Dan Aykroyd, Sigourney Weaver',
        'Three former parapsychology professors set up shop as a unique ghost removal service.', '4.jpg',
        ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Guardians of the Galaxy', 2014, 'Action', 121, 'PG-13', 'Chris Pratt, Vin Diesel, Bradley Cooper',
        'A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.',
        '5.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('John Wick', 2014, 'Action', 101, 'R', 'Keanu Reeves, Michael Nyqvist, Alfie Allen',
        'An ex-hit-man comes out of retirement to track down the gangsters that killed his dog and took everything from him.',
        '6.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Jumanji', 1995, 'Action', 104, 'PG-13', 'Robin Williams, Kirsten Dunst, Bonnie Hunt',
        'When two kids find and play a magical board game, they release a man trapped in it for decades - and a host of dangers that can only be stopped by finishing the game.',
        '7.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Mad Max 2: The Road Warrior', 1981, 'Action', 96, 'R', 'Mel Gibson, Bruce Spence, Michael Preston',
        'In the post-apocalyptic Australian wasteland, a cynical drifter agrees to help a small, gasoline-rich community escape a horde of bandits.',
        '8.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Mad Max: Fury Road', 2015, 'Action', 120, 'R', 'Tom Hardy, Charlize Theron, Nicholas Hoult',
        'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.',
        '9.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Mission: Impossible - Fallout', 2018, 'Action', 147, 'PG-13', 'Tom Cruise, Henry Cavill, Ving Rhames',
        'Ethan Hunt and his IMF team, along with some familiar allies, race against time after a mission gone wrong.',
        '10.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Pirates of the Caribbean: The Curse of the Black Pearl', 2003, 'Action', 143, 'PG-13',
        'Johnny Depp, Geoffrey Rush, Orlando Bloom',
        'Blacksmith Will Turner teams up with eccentric pirate "Captain" Jack Sparrow to save his love, the governor\'s daughter, from Jack\'s former pirate allies, who are now undead.',
        '11.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Star Wars: Episode IV - A New Hope', 1977, 'Action', 121, 'PG', 'Mark Hamill, Harrison Ford, Carrie Fisher',
        'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee, and two droids to save the galaxy from the Empire\'s world-destroying battle station.',
        '12.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('The Bourne Identity', 2002, 'Action', 119, 'PG-13', 'Matt Damon, Franka Potente, Chris Cooper',
        'A man is picked up by a fishing boat, bullet-riddled and suffering from amnesia, before racing to elude assassins and regain his memory.',
        '13.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('The Matrix', 1999, 'Action', 136, 'R', 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss',
        'A computer hacker learns about the true nature of reality and his role in the war against its controllers.',
        '14.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('The Terminator', 1984, 'Action', 107, 'R', 'Arnold Schwarzenegger, Linda Hamilton, Michael Biehn',
        'A human soldier is sent from 2029 to 1984 to stop an almost indestructible cyborg killing machine, sent from the same year, which has been programmed to execute a young woman whose unborn son is the key to humanity\'s future salvation.',
        '15.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Akira', 1988, 'Anime', 124, 'R', 'Mitsuo Iwata, Nozomu Sasaki, Mami Koyama',
        'A secret military project endangers Neo-Tokyo when it turns a biker gang member into a rampaging psychic psychopath who can only be stopped by two teenagers and a group of psychics.',
        '1.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('A Silent Voice', 2016, 'Anime', 130, 'PG-13', 'Miyu Irino, Saori Hayami, Aoi Yûki',
        'A young man isostracized by his classmates after he bullies a deaf girl to the point where she moves away. Years later, he sets off on a path for redemption.',
        '2.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Demon Slayer: Kimetsu No Yaiba - To the Swordsmith Village', 2023, 'Anime', 110, 'R',
        'Natsuki Hanae, Akari Kitô, Yoshitsugu Matsuoka',
        'Tanjiro needs to bring a definitive end to Upper Rank Six. After the dust settles, he goes with his sister Nezuko to the Swordsmith Village in search of a new sword.',
        '3.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Demon Slayer: Mugen Train', 2020, 'Anime', 117, 'R', 'Natsuki Hanae, Akari Kitô, Yoshitsugu Matsuoka',
        'Tanjiro and his demon-slaying companions board the Infinity Train on a mission to defeat a demon tormenting people and killing demon slayers.',
        '4.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Dragon Ball Super: Broly', 2018, 'Anime', 100, 'PG', 'Masako Nozawa, Aya Hisakawa, Ryô Horikawa',
        'Goku and Vegeta encounter Broly, a Saiyan warrior unlike any fighter they\'ve faced before.', '5.jpg',
        ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Grave of the Fireflies', 1988, 'Anime', 89, 'PG-13', 'Tsutomu Tatsumi, Ayano Shiraishi, Akemi Yamaguchi',
        'A young boy and his little sister struggle to survive in Japan during World War II.', '6.jpg',
        ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('My Neighbor Totoro', 1988, 'Anime', 86, 'G', 'Hitoshi Takagi, Noriko Hidaka, Chika Sakamoto',
        'When two girls move to the country to be near their ailing mother, they have adventures with the wondrous forest spirits who live nearby.',
        '7.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Nausicaä of the Valley of the Wind', 1984, 'Anime', 117, 'PG',
        'Sumi Shimamoto, Mahito Tsujimura, Hisako Kyôda',
        'Warrior and pacifist Princess Nausicaä desperately struggles to prevent two warring nations from destroying themselves and their dying planet.',
        '8.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Princess Mononoke', 1997, 'Anime', 134, 'PG-13', 'Yôji Matsuda, Yuriko Ishida, Yûko Tanaka',
        'On a journey to find the cure for a Tatarigami\'s curse, Ashitaka finds himself in the middle of a war between the forest gods and Tatara, a mining colony. In this quest, he also meets San, the Mononoke Hime.',
        '9.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Spirited Away', 2001, 'Anime', 125, 'PG', 'Rumi Hiiragi, Miyu Irino, Mari Natsuki',
        'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
        '10.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Weathering with You', 2019, 'Anime', 112, 'PG-13', 'Kotaro Daigo, Nana Mori, Shun Oguri',
        'A high-school boy who has run away to Tokyo befriends a girl who appears to be able to manipulate the weather.',
        '11.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2)),
       ('Your Name', 2016, 'Anime', 106, 'PG', 'Ryûnosuke Kamiki, Mone Kamishiraishi, Ryô Narita',
        'Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?',
        '12.jpg', ROUND(RAND() * (120.0 - 60.0) + 60.0, 2));